### ISSUE TITLE
Replace helm release diff with something better

### ISSUE THREAD

**Issue by buroa** [buroa/k8s-gitops#254]
The current js version is complete shit and bugs out constantly

**Comment by buroa** [comment]
Fixed https://github.com/buroa/k8s-gitops/commit/009225e430ba942a69c3c36723fb9989cb3332b7

**Comment by onedr0p** [comment]
Hey I spent quality time creating that script 😂

**Comment by buroa** [comment]
> Hey I spent quality time creating that script 😂

I know 😂 it bugs out sometimes but it's pretty rare now. Hopefully flux comes up with a real helmdiff :-)
